apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: default
data:
  RabbitMq__Host: "rabbitmq-service"
  ASPNETCORE_ENVIRONMENT: "Production"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__CatalogConnection: "Server=sqlserver-service;Database=Db_Jogos;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: fcg-catalog-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: catalog-config
        - secretRef:
            name: catalog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
spec:
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 
  type: ClusterIP